"""enforce one current salary

Revision ID: 34b6312593c6
Revises: c069002b0710
Create Date: 2026-09-19 22:51:54.837878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '34b6312593c6'
down_revision: Union[str, Sequence[str], None] = 'c069002b0710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_salary_records_current_employee', 'salary_records', ['employee_id'], unique=True, postgresql_where=sa.text('effective_to IS NULL'), sqlite_where=sa.text('effective_to IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_salary_records_current_employee', table_name='salary_records', postgresql_where=sa.text('effective_to IS NULL'), sqlite_where=sa.text('effective_to IS NULL'))
    # ### end Alembic commands ###