"""create salary records table

Revision ID: c069002b0710
Revises: 278f92928b55
Create Date: 2026-09-19 22:03:59.369065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'c069002b0710'
down_revision: Union[str, Sequence[str], None] = '278f92928b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('base_salary > 0', name='ck_salary_base_salary_positive'),
    sa.CheckConstraint('bonus >= 0', name='ck_salary_bonus_non_negative'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_salary_dates_valid'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_records_effective_from'), 'salary_records', ['effective_from'], unique=False)
    op.create_index(op.f('ix_salary_records_employee_id'), 'salary_records', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_records_employee_id'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_effective_from'), table_name='salary_records')
    op.drop_table('salary_records')
    # ### end Alembic commands ###